set_property IOSTANDARD LVCMOS33 [get_ports {IO0_7[0]}]
set_property PACKAGE_PIN T14 [get_ports {IO0_7[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO0_7[1]}]
set_property PACKAGE_PIN U12 [get_ports {IO0_7[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO0_7[2]}]
set_property PACKAGE_PIN U13 [get_ports {IO0_7[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO0_7[3]}]
set_property PACKAGE_PIN V13 [get_ports {IO0_7[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO0_7[4]}]
set_property PACKAGE_PIN V15 [get_ports {IO0_7[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO0_7[5]}]
set_property PACKAGE_PIN T15 [get_ports {IO0_7[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO0_7[6]}]
set_property PACKAGE_PIN R16 [get_ports {IO0_7[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO0_7[7]}]
set_property PACKAGE_PIN U17 [get_ports {IO0_7[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {IO8_11[0]}]
set_property PACKAGE_PIN V17 [get_ports {IO8_11[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO8_11[1]}]
set_property PACKAGE_PIN V18 [get_ports {IO8_11[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO8_11[2]}]
set_property PACKAGE_PIN T16 [get_ports {IO8_11[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IO8_11[3]}]
set_property PACKAGE_PIN R17 [get_ports {IO8_11[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports IO12]
set_property PACKAGE_PIN P18 [get_ports IO12]
set_property IOSTANDARD LVCMOS33 [get_ports IO13]
set_property PACKAGE_PIN N17 [get_ports IO13]

set_property IOSTANDARD LVCMOS33 [get_ports PMODA_0L]
set_property PACKAGE_PIN Y18 [get_ports PMODA_0L]
set_property IOSTANDARD LVCMOS33 [get_ports PMODA_0R]
set_property PACKAGE_PIN U18 [get_ports PMODA_0R]
set_property IOSTANDARD LVCMOS33 [get_ports PMODA_1L]
set_property PACKAGE_PIN Y19 [get_ports PMODA_1L]
set_property IOSTANDARD LVCMOS33 [get_ports PMODA_1R]
set_property PACKAGE_PIN U19 [get_ports PMODA_1R]

set_property IOSTANDARD LVCMOS33 [get_ports PMODB_0L]
set_property PACKAGE_PIN W14 [get_ports PMODB_0L]
set_property IOSTANDARD LVCMOS33 [get_ports PMODB_0R]
set_property PACKAGE_PIN V16 [get_ports PMODB_0R]

set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property PACKAGE_PIN N16 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property PACKAGE_PIN M14 [get_ports LED3]

set_property IOSTANDARD LVCMOS33 [get_ports PMODA_2R]
set_property IOSTANDARD LVCMOS33 [get_ports PMODA_2L]
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property PACKAGE_PIN Y16 [get_ports PMODA_2L]
set_property PACKAGE_PIN W18 [get_ports PMODA_2R]
set_property PACKAGE_PIN R14 [get_ports LED0]

set_property IOSTANDARD LVCMOS33 [get_ports {LED4[0]}]
set_property PACKAGE_PIN M14 [get_ports {LED4[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports LED_1]
set_property PACKAGE_PIN P14 [get_ports LED_1]
set_property PACKAGE_PIN Y14 [get_ports PMODB1L]
set_property PACKAGE_PIN W16 [get_ports PMODB1R]
set_property PACKAGE_PIN T11 [get_ports PMODB2L]
set_property PACKAGE_PIN V12 [get_ports PMODB2R]
set_property IOSTANDARD LVCMOS33 [get_ports PMODB1L]
set_property IOSTANDARD LVCMOS33 [get_ports PMODB1R]
set_property IOSTANDARD LVCMOS33 [get_ports PMODB2L]
set_property IOSTANDARD LVCMOS33 [get_ports PMODB2R]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
