set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN H16 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports {PHA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {POL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RSTn[0]}]
set_property PACKAGE_PIN T14 [get_ports {PHA[0]}]
set_property PACKAGE_PIN U12 [get_ports {POL[0]}]
set_property PACKAGE_PIN U17 [get_ports {RSTn[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports LED_0]
set_property IOSTANDARD LVCMOS33 [get_ports LED_1]
set_property PACKAGE_PIN R14 [get_ports LED_0]
set_property PACKAGE_PIN P14 [get_ports LED_1]
set_property IOSTANDARD LVCMOS33 [get_ports BTN0]
set_property IOSTANDARD LVCMOS33 [get_ports SW0]
set_property IOSTANDARD LVCMOS33 [get_ports SW1]
set_property PACKAGE_PIN M20 [get_ports SW0]
set_property PACKAGE_PIN M19 [get_ports SW1]
set_property PACKAGE_PIN D19 [get_ports BTN0]

set_property IOSTANDARD LVCMOS33 [get_ports MISORX]
set_property IOSTANDARD LVCMOS33 [get_ports MISOTX]
set_property IOSTANDARD LVCMOS33 [get_ports MOSIRX]
set_property IOSTANDARD LVCMOS33 [get_ports MOSITX]
set_property PACKAGE_PIN W14 [get_ports MISORX]
set_property PACKAGE_PIN W16 [get_ports MOSIRX]
set_property PACKAGE_PIN R17 [get_ports MOSITX]
set_property PACKAGE_PIN P18 [get_ports MISOTX]

set_property IOSTANDARD LVCMOS33 [get_ports TXCSn]
set_property PACKAGE_PIN T16 [get_ports TXCSn]
set_property IOSTANDARD LVCMOS33 [get_ports TXSPI_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RXSPI_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports RXCSn]
set_property PACKAGE_PIN Y14 [get_ports RXCSn]
set_property PACKAGE_PIN V16 [get_ports RXSPI_CLK]
set_property PACKAGE_PIN N17 [get_ports TXSPI_CLK]


set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_1]


