set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CLK_out]
set_property IOSTANDARD LVCMOS33 [get_ports {cs_out_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports miso_in_0]
set_property IOSTANDARD LVCMOS33 [get_ports mosi_out_0]
set_property IOSTANDARD LVCMOS33 [get_ports {pha_out_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pol_out_0[0]}]
set_property PACKAGE_PIN T16 [get_ports {cs_out_0[0]}]
set_property PACKAGE_PIN P18 [get_ports miso_in_0]
set_property PACKAGE_PIN R17 [get_ports mosi_out_0]
set_property PACKAGE_PIN T14 [get_ports {pha_out_0[0]}]
set_property PACKAGE_PIN N17 [get_ports SPI_CLK_out]
set_property PACKAGE_PIN H16 [get_ports clk_in1_0]
set_property PACKAGE_PIN U12 [get_ports {pol_out_0[0]}]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
